num1=int(input("Enter the value of num1\t"));
num2=int(input("Enter the value of num2\t"));
sum=num1+num2;
mul=num1*num2;
sub=num1-num2;
div=num1/num2;
print("sum : ",sum);
print("mul : ",mul);
print("sub : ",sub);
print("div : ",div);
